//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanHang.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string short_des { get; set; }
        public string full_des { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> price_discount { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> show_on_home_page { get; set; }
        public Nullable<int> display_order { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string avatar { get; set; }
        public Nullable<int> soluong { get; set; }
    }
}
